# Generated by Django 3.1.4 on 2022-09-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
