# Generated by Django 3.1.4 on 2022-09-12 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, null=True, verbose_name='NAME')),
                ('desc', models.TextField(null=True, verbose_name='DESC')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='CREATE TIME')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UPDATE TIME')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commodity_user_id', to=settings.AUTH_USER_MODEL, verbose_name='COMMODITY USER ID')),
            ],
            options={
                'verbose_name': 'Commodity',
                'verbose_name_plural': 'Commodity',
            },
        ),
        migrations.CreateModel(
            name='Trolley',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, null=True, verbose_name='NICK NAME')),
                ('desc', models.CharField(max_length=254, unique=True, verbose_name='EMAIL')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='CREATE TIME')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UPDATE TIME')),
                ('commodity', models.ManyToManyField(related_name='to_commodity', to='commodity.Commodity', verbose_name='TO COMMODITY')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trolley_user_id', to=settings.AUTH_USER_MODEL, verbose_name='TROLLEY USER ID')),
            ],
            options={
                'verbose_name': 'Trolley',
                'verbose_name_plural': 'Trolley',
            },
        ),
    ]
